### ISSUE TITLE
Toggle and transition javascript.

### ISSUE THREAD

**Issue by KimberlyYen** [Rabbittee/JavaScript30#26]
在Js30影片範例中，他用了add, remove方式完成 transition ，`classList.Toggle(  ) `是否能直接微調數值，達到一樣的效果呢？

附上我正在查找的連結：
- [imple Toggle Switch With Expanding Background](https://codepen.io/kiran-r-raj/pen/XWpwWzK) 這支好像可以！
- [10 Simple Toggle Switch Animation Using CSS And JavaScript](https://dev.to/kiranrajvjd/10-simple-toggle-switch-animation-using-css-and-javascript-3gpn)
- [Toggle Visibility When Hiding Elements](https://css-tricks.com/snippets/css/toggle-visibility-when-hiding-elements/)

**Comment by KimberlyYen** [comment]
我成功了！

```js
  // Correct & Change style
  const audioDivClass = document.querySelector(`div[data-key='${keyCurrent}']`);
  audioDivClass.classList.toggle("playing");
```

```css
.key {
  border: 0.4rem solid black;
  border-radius: 0.5rem;
  margin: 1rem;
  font-size: 1.5rem;
  padding: 1rem 0.5rem;
 
  // 刪掉這一行
  /* transition: all 5000ms ease; */
  width: 10rem;
  text-align: center;
  color: white;
  background: rgba(0, 0, 0, 0.4);
  text-shadow: 0 0 0.5rem black;
}

.playing {
  transform: scale(1.5);
  border-color: #ffc600;
  box-shadow: 0 0 1rem #ffc600;

  // 加了這一行
  transition: all 3000ms cubic-bezier(0.175, 0.885, 0.32, 1.275);
}
```
